### model
model_name_or_path: /ai4good1-shared/liyu/egoavu/models/Qwen2.5-Omni-7B-thinker-train
adapter_name_or_path: /ai4good1-shared/liyu/egoavu/release/EgoAVU-Qwen2.5-Omni-7B-LoRA-r20k
trust_remote_code: true
flash_attn: fa2
video_fps: 2.0
video_maxlen: 64
video_max_pixels: 200704
use_audio_in_video: true
### method
stage: sft
do_predict: true
predict_with_generate: true
finetuning_type: lora
### dataset
eval_dataset: egoavu_bench_eval_s0of8
dataset_dir: /ai4good1-shared/liyu/egoavu/bench_infer/data
template: qwen2_omni
cutoff_len: 32768
overwrite_cache: true
preprocessing_num_workers: 32
dataloader_num_workers: 4
### output
output_dir: /ai4good1-shared/liyu/egoavu/bench_infer/runs/r20k8g/egoavu_bench_eval_s0of8
overwrite_output_dir: true
report_to: none
### eval / generation
per_device_eval_batch_size: 1
bf16: true
do_sample: false
max_new_tokens: 1024
repetition_penalty: 1.0
ddp_timeout: 180000000
